### ISSUE TITLE
something broke; probsbly the Deck.adddiscardpilebacktoDeck()

### ISSUE THREAD

**Issue by danielbrackett** [danielbrackett/BlackJack#11]
something broke; probably the Deck.adddiscardpilebacktoDeck()

Will look into this shortly. 

Exception in thread "main" java.lang.NullPointerException
	at java.base/java.util.ArrayDeque.addLast(ArrayDeque.java:304)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1380)
	at java.base/java.util.ArrayDeque.addAll(ArrayDeque.java:326)
	at Deck.shuffle(Deck.java:45)
	at Deck.addDiscardPileBackToDeck(Deck.java:117)
	at GameRunner.timeToRefreshTheDeck(GameRunner.java:233)
	at GameRunner.run(GameRunner.java:70)
	at Main.main(Main.java:10)

**Comment by danielbrackett** [comment]
The issue has yet to re-occur. Will continue to test. I think that issue may have been related to extended play and reshuffle. still unclear. Must explore multiple avenues to understand the issue.
